[General]
background=
font="Noto Sans"
fontSize=10
clockFont="Noto Sans"
logo="/usr/share/pixmaps/caelaris-logo.svg"
userBadge="Caelaris Linux"
showClock=true
timeFormat="hh:mm AP"
dateFormat="dddd, MMMM d"
