---
dontChroot: false
timeout: 100
script:
    - "-rm -rvf /etc/sudoers.d/g_wheel"
    - "-userdel -rf liveuser"
    - "systemctl enable NetworkManager"
    - "systemctl enable sddm || systemctl enable gdm"
