---
dontChroot: false
timeout: 120
script:
    - "-rm -rvf /etc/sudoers.d/g_wheel"
    - "-rm -rvf /etc/sudoers.d/liveuser"
    - "-rm -rvf /etc/sddm.conf.d/autologin.conf"
    - "-rm -rvf /etc/systemd/system/graphical.target.wants/caelaris-live-setup.service"
    - "-rm -rvf /etc/systemd/system/caelaris-live-setup.service"
    - "-rm -rvf /etc/skel/Desktop/install-caelaris.desktop"
    - "-rm -rvf /etc/skel/Desktop/switch-to-*.desktop"
    - "-userdel -rf liveuser"
    - "systemctl enable NetworkManager"
    - "systemctl enable sddm"
    - "systemctl enable vmtoolsd || true"
    - "systemctl enable vboxservice || true"
    - "systemctl enable spice-vdagentd || true"
    - "systemctl enable ananicy-cpp || true"
    - "pacman-key --init || true"
    - "pacman-key --populate archlinux || true"
    - "grub-mkconfig -o /boot/grub/grub.cfg || true"
