---
showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    false
showDonateUrl:          false

requirements:
    requiredStorage:    15.0
    requiredRam:        2.0
    internetCheckUrl:   https://archlinux.org
    check:
        - storage
        - ram
        - power
        - internet
        - root
    required:
        - storage
        - ram
        - root
