# Type Name     ID  GECOS             Home directory  Shell
u      liveuser 1000 "Caelaris Linux"  /home/liveuser  /bin/bash
m      liveuser wheel
m      liveuser video
m      liveuser audio
m      liveuser optical
m      liveuser storage
m      liveuser input
m      liveuser power
